name: Setup
description: Setup Env

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Setup Java Env
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: gradle

    - name: Install dependencies
      shell: bash
      run: npm ci --no-audit --no-fund
