import { createStyle } from '@/utils/tools'

export const styles = createStyle({
  root: { flex: 1 },
  scroll: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  content: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  brand: { alignItems: 'center', marginBottom: 28 },
  brandMark: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  title: { fontWeight: '700', letterSpacing: 0.2 },
  subtitle: { marginTop: 8, textAlign: 'center', lineHeight: 21 },
  form: { gap: 14 },
  field: { gap: 7 },
  fieldLabel: { fontWeight: '600' },
  inputShell: {
    minHeight: 50,
    borderWidth: 1,
    borderRadius: 14,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  input: { height: 42, paddingHorizontal: 0 },
  primaryButton: {
    minHeight: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  secondaryButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  codeRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  codeField: { flex: 1 },
  codeButton: {
    minHeight: 50,
    paddingHorizontal: 15,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  error: { borderRadius: 12, paddingHorizontal: 13, paddingVertical: 10, lineHeight: 19 },
  linkRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 8 },
  link: { fontWeight: '600' },
  bindingNotice: { borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, lineHeight: 20 },
})
